// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AttendanceService records student attendance. It replaces the /submit-signin
 * and /submit-major endpoints of the Flask version.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sheets$0 from "./internal/sheets/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * SignIn records a sign-in for a student who has signed in before.
 * 
 * A student the directory has never seen is not recorded: the frontend sends
 * them to the major screen and calls SignInWithMajor instead.
 */
export function SignIn(student: sheets$0.Student): $CancellablePromise<$models.SignInOutcome> {
    return $Call.ByID(2675307980, student);
}

/**
 * SignInWithMajor adds a first-time student to the directory and records their
 * sign-in in one step.
 */
export function SignInWithMajor(student: sheets$0.Student): $CancellablePromise<void> {
    return $Call.ByID(767977889, student);
}
