// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the setup state the Settings screen renders.
 */
export interface Settings {
    /**
     * SpreadsheetID is the attendance spreadsheet this app writes to.
     */
    "spreadsheetId": string;

    /**
     * HasCredentials reports whether a Google OAuth credentials.json has been added.
     */
    "hasCredentials": boolean;

    /**
     * IsAuthorized reports whether someone has signed in with a Google account.
     */
    "isAuthorized": boolean;

    /**
     * ConfigDir is where all of the above is stored, shown so it can be found on disk.
     */
    "configDir": string;
}

/**
 * SignInOutcome tells the frontend which screen to show after a sign-in attempt.
 */
export enum SignInOutcome {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * OutcomeSignedIn means the sign-in was recorded; show the welcome screen.
     */
    OutcomeSignedIn = "signed-in",

    /**
     * OutcomeNeedsMajor means this student is not in the directory yet and has to
     * pick a major before the sign-in can be recorded.
     */
    OutcomeNeedsMajor = "needs-major",
};
