// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService configures the Google Sheets connection. The Flask version
 * required hand-editing sheetInfo.json and dropping credentials.json next to the
 * source; a packaged app has neither, so this is exposed in the UI instead.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Authorize signs in to the Google account that owns the attendance spreadsheet,
 * via the browser. It blocks until the browser flow finishes.
 */
export function Authorize(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(1507947871);
}

/**
 * ChooseCredentialsFile opens a native file picker for the credentials.json
 * downloaded from the Google Cloud console and stores a copy.
 * 
 * Choosing nothing is not an error: it returns the unchanged settings.
 */
export function ChooseCredentialsFile(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(1594417727);
}

/**
 * Get returns the current setup state.
 */
export function Get(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(710695688);
}

/**
 * OpenConfigDir reveals the configuration directory in the file manager.
 */
export function OpenConfigDir(): $CancellablePromise<void> {
    return $Call.ByID(2085208945);
}

/**
 * SetSpreadsheetID stores the attendance spreadsheet id. It accepts either a
 * bare id or a full spreadsheet URL.
 */
export function SetSpreadsheetID(value: string): $CancellablePromise<$models.Settings> {
    return $Call.ByID(5194603, value);
}

/**
 * SignOut forgets the saved Google authorisation.
 */
export function SignOut(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3253070295);
}
