// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Student is one person signing in.
 */
export interface Student {
    "firstName": string;
    "lastName": string;
    "studentId": string;
    "major"?: string;
}
